apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: star-wars-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: star-wars-deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
