apiVersion: apps/v1
kind: Deployment
metadata:
  name: star-wars-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: star-wars
  template:
    metadata:
      labels:
        app: star-wars
    spec:
      containers:
        - name: star-wars
          image: ghcr.io/claygorman/k8s-sample:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
