apiVersion: v1
kind: Service
metadata:
  name: star-wars-service
spec:
  type: LoadBalancer
  selector:
    app: star-wars
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
